name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # ou a branch principal do seu projeto

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.0'  # Atualize para a versão necessária do Node.js

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Export the project
      run: npm run export

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out  # ou o diretório de saída do seu projeto
